[font]
normal = { family = "0xProto Nerd Font Mono", style = "Regular" }
bold = { family = "0xProto Nerd Font Mono", style = "Bold" }
italic = { family = "0xProto Nerd Font Mono", style = "Italic" }
bold_italic = { family = "0xProto Nerd Font Mono", style = "Bold Italic" }
[window]
option_as_alt = "both"
